version: "3.5"

services:
  frontend:
    image: node:14-bullseye
    container_name: frontend
    env_file: ./.env
    working_dir: /app
    ports:
      - $FRONTEND_LOCAL_PORT:3000
    volumes:
      - ./frontend:/app
    entrypoint: "npm start"
  backend:
    image: node:18.16.1-slim
    container_name: backend
    env_file: ./.env
    working_dir: /app
    ports:
      - $BACKEND_LOCAL_PORT:3000
    volumes:
      - ./backend:/app
    entrypoint: "npm start"
